### ISSUE TITLE
Rewrite Article Options

### ISSUE THREAD

**Issue by fransyozef** [bartdeijkers/selligent-modular-email-template#11]
At this moment, we put a lot of options in the Article Options. I suggest to break this up in to 

- Article options
-- paddings
-- mobile full width
-- advertorial
-- divider

- Image options
-- paddings
-- image above title

- Social Share Options
-- fb share 
-- whatsapp share
-- twitter share
-- whatsapp share
-- mail share
-- google plus share

Not sure to put TITLE/SUBTITLE/CONTENT options in Article options or just create options for each one of them

**Comment by bartdeijkers** [comment]
Extra options is no longer necessary. The new approach is to implement the GETPROP() function to stack multiple options/fields in a single field.

For instance: the 'IMAGE' field is now renamed to 'MEDIA'.
In order to add multiple images for a image carousel you can now enter multple image locations separated by the pipe '|' symbol.
image1.jpg|image2.jpg

Extra advantage of GETPROP() is that it allows the output to be further validated. This gives the option to validate file extension for MEDIA and recognise if we should display for image or video.

GETPROP() is also great for applying button presets. This will be available for the next version v3.0.2.
