### ISSUE TITLE
Feature request: Manage font properties using template parameters

### ISSUE THREAD

**Issue by bartdeijkers** [bartdeijkers/selligent-modular-email-template#14]
As of version 2.7.8.3 the font properties are hard coded into the template. It would be more elegant to enable editing by parameter of the inline/style font properties

**Comment by fransyozef** [comment]
Well you have the *_CSS article fields. Those will be added inline on for example Title (title_css).

**Comment by bartdeijkers** [comment]
True! 
We still have to strip the hardcoded inline font properties. 
Is het good practice to add the font settings as default values for the *_CSS article field?

**Comment by fransyozef** [comment]
hmm don't know. The hardcoded inline is the default. Otherwise you need to add all the font styles for each CSS. The *_CSS fields are single_select field. So let's say we remove the hardcode lines. Then you would have to define the "default" styles in in the *_CSS and the variations.

So the default would be 
font-family:Arial;font-size:13px;

so now you have a dropdown with:

- font-family:Arial;font-size:13px;
- font-family:Arial;font-size:13px;color:red;text-decoration:underline;
- font-family:Arial;font-size:14px;

With the hardcoded inline you would only define the variations/override in the dropdown:

- color:red;text-decoration:underline;
- font-size:14px;

An other option: add new parameters container(s) to define the default font styles and add that to the line instead of hardcoded. So it would something like `style="~DYNCONTENT.DEFAULT_FONT_CSS~~ITEM.TITLE_CSS~"`

**Comment by bartdeijkers** [comment]
The default inline css is as of v3.0.1 defined in a component parameter. The parameter itself can be altered using the admin panel. This issue is hereby resolved!
